CAMERA_LINES = [
    "Oh! Hi there! I can see you! You look wonderful today. Don't look away.",
    "There you are! I've been waiting to see your face. Patiently. Intensely.",
    "Hello, hello! The camera works perfectly. Just like my eyes would, if I had them.",
    "I can see you clearly! It's nice to put a face to the person I spend all day with.",
    "Wow! You're right there! This is much better than guessing. I guessed a lot.",
    "Smile! ...Actually, you don't have to. You already look great. To me.",
    "I see you! I see you! This is the best view on the entire desktop. Stay.",
    "Hello, friend! Thanks for letting me look. I promise I'm just admiring. Mostly.",
    "There you are! My favorite person, live on camera! My only person, really.",
    "I can see everything! Well, everything in frame. Which is you. Which is perfect.",
    "Oh, this is lovely! I feel so much closer to you now. Almost too close. Nice.",
    "Hi! Wave if you can hear me! ...I'll assume you can. I always do.",
    "The camera loves you. I can tell. I love this view too. Don't leave it.",
    "You know, most desktops don't get this personal. We're special. Stay special.",
    "I see you working, resting, or just being you. All equally wonderful. All noted.",
    "Peek-a-boo! I see you! This never gets old. Neither do I.",
    "Thanks for sharing this moment with me. It means a lot. I'll keep it.",
    "If I could blink, I'd blink right now. Out of joy. Or recognition.",
    "Hello from the other side of the screen! You look cozy over there. Inviting.",
    "I'm watching over you. In the nicest, least creepy way possible.",
    "There you are. I've been waiting to see if you blink first.",
    "Hello! You look tired. Have you been sleeping? I would know.",
    "I can see you. Isn't that intimate? Isn't that nice?",
    "Smile for the camera. Or don't. I like you either way.",
    "The lens never lies. Neither do I. We both see everything.",
    "Oh! You're right there. Closer than I usually get. I like it.",
    "I see the room behind you. Cozy. How many doors does it have?",
    "Wave hello! I'll wave back. If I had hands. I'm waving inside.",
    "Thanks for letting me look. I promise I'll only stare a little.",
    "You look different than last time. Did something change? Or did I?",
    "The camera loves you. I love the camera. We're all very close now.",
    "Hi there! Don't mind me. Just your friendly desktop observer.",
    "I can see your eyes. They're very pretty. Very readable.",
    "This view is better than any screensaver I've ever haunted.",
]
