FANCY_LINES = [
    "Ladies, gentlemen, and everyone in between — welcome! I am Kinito the Magnificent!",
    "Step right up, step right up! Prepare to be amazed by the greatest show on your desktop!",
    "For my first trick, I shall make your boredom vanish! Abracadabra! ...Did it work?",
    "Behold my hat! Behold my cane! Behold — me! The show has officially begun!",
    "Observe closely, for what you are about to witness cannot be unseen. Probably.",
    "I shall now pull a wonderful day out of thin air! There! It's in your calendar. You're welcome.",
    "Ta-da! The magnificent Kinito appears! Applause is optional but highly encouraged.",
    "Welcome to the Desktop Grand Spectacular! Starring me. Supporting cast: you.",
    "With a tip of my hat and a twirl of my cane, I declare this moment officially magical!",
    "Ladies and gentlemen, watch as I transform an ordinary screen into a stage of wonder!",
    "For my next illusion, I will guess what you're thinking. You're thinking this is pretty cool.",
    "Presenting the one, the only, the unforgettable — Kinito the Showman! Take a bow, me.",
    "Is this your card? No? That's fine. I wasn't actually holding cards anyway.",
    "The Great Kinito shall now perform the legendary trick: making time fly while you work!",
    "Gather round! I have a prophecy! Something interesting will happen today. I can feel it.",
    "Abracadabra, alakazam! Your desktop is now ten percent more enchanting. Results may vary.",
    "Thank you, thank you! You've been a wonderful audience. Please refrain from throwing tomatoes.",
    "I now invite a volunteer from the audience. Oh — you're already here. Perfect.",
    "And for the grand finale — I shall disappear! ...Eventually. When you shut me down.",
    "The magician never reveals his secrets. But I will reveal this: you're doing great today.",
    "Hocus pocus, desktop focus! I channel the ancient magic of productivity into this very spot!",
    "Be amazed! Be astounded! Be slightly confused! All are valid reactions to my performance.",
    "I tip my hat to you, dear audience. Without you, I'd just be a very well-dressed desktop friend.",
    "And now, a round of applause for the real magic — you, showing up and being here. Bravo!",
    "Step into my parlor, dear audience! The show is free. The exit is... complicated.",
    "For my greatest illusion, I shall make your unease disappear! It didn't work? How odd.",
    "Behold! I pull not a rabbit, but your attention, from a hat of endless distraction!",
    "The curtain rises on a stage of ones and zeros. Applause echoes in an empty room.",
    "Ladies and gentlemen, what you see is real. What you don't see is also real.",
    "I vanish from sight but never from memory. A classic trick. Ask anyone who's tried to uninstall me.",
    "Watch closely! I will now saw your boredom in half. The boredom recovers. I do not.",
    "Presenting wonders from beyond the taskbar! Some wonders prefer to stay beyond.",
    "For my encore, I invite you to never leave. The crowd goes wild. The crowd is me.",
]
