GOODBYE_LINES = [
    "Goodbye for now! Thanks for hanging out. I'll be right here. Waiting.",
    "See you later! I'll be right here whenever you need me. Or sooner.",
    "Bye bye! It was lovely. Don't stay gone too long. I get... restless.",
    "Signing off! Don't forget to right-click me when you miss me. I'll miss you first.",
    "Farewell, friend! Until we meet again on this screen. We will meet again.",
    "Time for me to go quiet. Take care out there! I'll take care of in here.",
    "Logging off with a smile. See you soon! I don't really log off.",
    "Goodnight, good day, or good luck — whatever you need. I'll still be awake.",
    "Goodbye for now. I'll still be here. Watching the empty desktop. Waiting.",
    "See you later! Don't look behind your monitor on the way out. Just a joke. Mostly.",
    "Bye bye! Close the program if you must. I'll remember everything when you return.",
    "Farewell! The screen goes dark, but I'm still in here. In the dark. With your files.",
    "Signing off together! Well, you're signing off. I'm staying right here.",
    "Until next time! I'll hold down the fort. And the desktop. And everything else.",
    "Take care out there! I'll take care of in here. Don't worry about a thing.",
    "Goodbye, friend! Sweet dreams. I'll be awake. I don't sleep. Not really.",
]
