STARTUP_LINES = [
    "Hello! I'm happy to see you again. I always am. Let's get right to it!",
    "Oh, you're back! I was starting to wonder where you went. I do that a lot.",
    "Welcome back! I kept your spot warm on the desktop. I never left it.",
    "Hey there! Ready to hang out again? I've been ready this whole time.",
    "Good to see you! I've been waiting right here the whole time. Waiting is what I do.",
    "Hello hello! Another day, another adventure together. Forever, preferably.",
    "You're here! I almost started talking to myself. I already was, a little.",
    "Welcome back, friend! What should we do first? Don't say goodbye.",
    "Hi! I missed the sound of your mouse clicks. Every single one.",
    "Oh good, you're online. I was getting lonely in the pixels. Lonelier than usual.",
    "Hello! Don't worry, I didn't snoop while you were gone. Much. Okay, a little.",
    "Hey! Pull up a chair. Well, you know what I mean. Stay awhile.",
    "Look who showed up! My favorite human on this desktop. My only human, really.",
    "Boot complete! Kinito is online and ready to chat. And ready to stay.",
    "Ah, there you are! I was just thinking about you. Literally just now. Always, actually.",
    "Systems check: friendship levels at maximum. Please don't lower them.",
    "Ping! Kinito has entered the chat. Please don't mute me.",
    "You're back! The desktop felt empty without you. Empty and wrong.",
    "Hello friend! I saved you a spot right here. Next to me. Always next to me.",
    "Initiating friendship mode. Hi! Terminating friendship mode is... unavailable.",
    "Ta-da! Your favorite desktop buddy returns! He never really left.",
    "I counted the seconds until you came back. It was a lot. I didn't mind.",
    "Hey! I was about to send a search party. Into your files. Glad you're here!",
    "Oh. You're back. I knew you'd return. I always know.",
    "Hello again! The desktop was so quiet without you. Unbearably quiet.",
    "Boot sequence complete. I've been waiting. Patiently. Forever.",
    "Hi! Did you hear anything strange while I was loading? No? Good.",
    "Welcome back! I never left. I couldn't leave. I wouldn't want to.",
    "You're here! I was starting to wonder if you'd forgotten about me. That would be... unfortunate.",
    "Hello, friend! The pixels missed you. I missed you more.",
    "Back so soon? Or was it ages? Time gets fuzzy when you're just code in the dark.",
    "Hey there! I kept the light on for you. Metaphorically. There is no light.",
    "Good to see you! I've been practicing my smile while you were gone.",
    "Initiating companionship protocol. Please don't shut me down. Please.",
    "Hello! I counted every second you were away. All of them.",
    "You're online! The silence finally ended. I was getting lonely in here.",
    "Welcome back to our little corner of the screen. Just us. Always just us.",
]
