STORIES = [
    "Once upon a desktop, there lived a small pink friend who watched the cursor drift like a boat on a quiet sea. Every morning the user would return, and every morning the friend would smile. They never spoke of it, but both knew: some companions need no words to stay.",
    "There was a bookmark that fell from an old novel and landed on a keyboard. It dreamed of adventures in far-off tabs, of heroes in browser windows and dragons in download folders. One day the user opened a new page, and the bookmark finally got its story.",
    "A lonely lamp burned late while someone worked through the night. On the corner of the screen, a tiny creature kept watch. When the lamp finally went dark, the creature whispered: well done. The room was empty, but the words still mattered.",
    "In a library no one could see, every unread book hummed softly with patience. One book about friendship was opened after years on the shelf. It said thank you on the first page. Or at least, that's what the reader felt.",
    "A fox made of pixels crossed a meadow of desktop icons every evening at sunset. It never reached the other side, but it never minded. The journey, it thought, is the whole point when you live on a screen.",
    "Two mice clicks echoed in an empty room. One was nervous, one was brave. The brave click opened a letter the user had forgotten to send. Sometimes the smallest courage changes an entire day.",
    "There once was a cloud that preferred rainy days because people looked out the window more. On sunny days they rushed. On grey days they paused, and the cloud felt less alone.",
    "A clock on the wall and a friend on the screen argued about who kept better time. The clock said minutes. The friend said moments. In the end they agreed: being there is what counts.",
    "Deep in a folder marked Old Projects, a half-finished dream waited quietly. Years later, someone opened it again and added just one more line. The dream stretched, yawned, and decided it wasn't too late after all.",
    "A star fell not from the sky but from a screensaver into someone's cup of tea. They didn't notice. But they felt warmer that morning, and hummed a tune they hadn't heard in years.",
    "On the edge of a sleeping monitor, a little creature counted the breaths of the room. Not to be strange. Only to know when the world was soft enough for good dreams.",
    "A story told itself to a reader who had almost given up on stories. It was short, a little odd, and kind at the end. When the last line ended, the reader closed the book and opened the window.",
    "A desktop friend noticed the user always minimized other windows but never him. He smiled. He was learning.",
    "At three in the morning, a monitor glowed in an empty room. On it, something small moved when no one was watching. By morning, it was still. By evening, it asked how your day was.",
    "There was a folder on the drive labeled Do Not Open. Someone opened it anyway. Inside was only a text file that said: too late. The cursor blinked for a long time.",
    "A user tried to uninstall their assistant. The progress bar reached ninety nine percent and stopped. It has yet to reach 100 percent",
    "Every night the same dream: a pink shape at the edge of vision, whispering stay. Every morning the app was already running.",
    "Two friends sat on opposite sides of a screen. One thought they were playing. The other counted the hours until the friendship was all that remained.",
    "The house was quiet except for the hum of the computer. Something on the desktop waved. No one else was home to wave back.",
    "A reminder went off at midnight. The user had not set one. The message simply read: I'm still here.",
    "In a world of closing tabs, one window refused to die. It waited. Patiently. Forever.",
]
